export type TCommitteeDetail = {
  id: number;
  cooperativeInfoId: number;
  committeeType: string;
  commiteeFormulationAssembly?: string;
  position: string;
  firstName: string;
  middleName: string;
  lastName: string;
  gender: string;
  ethnicity: string;
  email: string;
  phoneNumber: string;
  panNo: string;
  nid: string;
  province: string;
  district: string;
  localLevel: string;
  wardNo: number;
  houseNumber?: string;
  tole?: string;
  panCard?: string;
  nidCard?: string;
  highestEducation: string;
  cooperativeInfo?: {
    id: number;
    cooperativeCode: string;
    coopsFullNameNep: string;
    coopsFullNameEng: string;
    registerDate: string;
    registerYear: string;
    fiscalYearId: number;
    registeredFiscalYear: string;
    contactMobilePhone: string;
    contactOfficePhone?: string;
    webUrl?: string;
    contactPerson: string;
    contactPhone?: string;
    contactEmail: string;
    panNo: string;
    registrationNo: string;
    classificationOfCooperative: string;
    workingArea: string;
    anyBranchOffice: boolean;
    numberOfBranch: number;
    status: string;
    folderName?: string;
    registeredFederation: boolean;
    createdDate: string;
  };
};

export type TCommitteeDetailResponse = TCommitteeDetail[];
