/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DebugAuthRouteImport } from './routes/debug-auth'
import { Route as CooperativeFormRouteImport } from './routes/cooperative-form'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVerifyDetailRouteImport } from './routes/_authenticated/verify-detail'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedFiscalYearRouteImport } from './routes/_authenticated/fiscal-year'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCooperativeMemberListRouteImport } from './routes/_authenticated/cooperative-member-list'
import { Route as AuthenticatedCooperativeListRouteImport } from './routes/_authenticated/cooperative-list'
import { Route as AuthenticatedCoopProfileRouteImport } from './routes/_authenticated/coop-profile'
import { Route as AuthenticatedCompleteRegistrationRouteImport } from './routes/_authenticated/complete-registration'
import { Route as AuthenticatedReportsSummaryRouteImport } from './routes/_authenticated/reports/summary'
import { Route as AuthenticatedReportsDetailRouteImport } from './routes/_authenticated/reports/detail'
import { Route as AuthenticatedCooperativeVerificationIdRouteImport } from './routes/_authenticated/cooperative-verification/$id'
import { Route as AuthenticatedCooperativeDetailsIdRouteImport } from './routes/_authenticated/cooperative-details.$id'
import { Route as AuthenticatedCommitteeDetailsIdRouteImport } from './routes/_authenticated/committee-details.$id'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugAuthRoute = DebugAuthRouteImport.update({
  id: '/debug-auth',
  path: '/debug-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CooperativeFormRoute = CooperativeFormRouteImport.update({
  id: '/cooperative-form',
  path: '/cooperative-form',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVerifyDetailRoute =
  AuthenticatedVerifyDetailRouteImport.update({
    id: '/verify-detail',
    path: '/verify-detail',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFiscalYearRoute = AuthenticatedFiscalYearRouteImport.update({
  id: '/fiscal-year',
  path: '/fiscal-year',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCooperativeMemberListRoute =
  AuthenticatedCooperativeMemberListRouteImport.update({
    id: '/cooperative-member-list',
    path: '/cooperative-member-list',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCooperativeListRoute =
  AuthenticatedCooperativeListRouteImport.update({
    id: '/cooperative-list',
    path: '/cooperative-list',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoopProfileRoute =
  AuthenticatedCoopProfileRouteImport.update({
    id: '/coop-profile',
    path: '/coop-profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompleteRegistrationRoute =
  AuthenticatedCompleteRegistrationRouteImport.update({
    id: '/complete-registration',
    path: '/complete-registration',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsSummaryRoute =
  AuthenticatedReportsSummaryRouteImport.update({
    id: '/reports/summary',
    path: '/reports/summary',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsDetailRoute =
  AuthenticatedReportsDetailRouteImport.update({
    id: '/reports/detail',
    path: '/reports/detail',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCooperativeVerificationIdRoute =
  AuthenticatedCooperativeVerificationIdRouteImport.update({
    id: '/cooperative-verification/$id',
    path: '/cooperative-verification/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCooperativeDetailsIdRoute =
  AuthenticatedCooperativeDetailsIdRouteImport.update({
    id: '/cooperative-details/$id',
    path: '/cooperative-details/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommitteeDetailsIdRoute =
  AuthenticatedCommitteeDetailsIdRouteImport.update({
    id: '/committee-details/$id',
    path: '/committee-details/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cooperative-form': typeof CooperativeFormRoute
  '/debug-auth': typeof DebugAuthRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/complete-registration': typeof AuthenticatedCompleteRegistrationRoute
  '/coop-profile': typeof AuthenticatedCoopProfileRoute
  '/cooperative-list': typeof AuthenticatedCooperativeListRoute
  '/cooperative-member-list': typeof AuthenticatedCooperativeMemberListRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fiscal-year': typeof AuthenticatedFiscalYearRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/verify-detail': typeof AuthenticatedVerifyDetailRoute
  '/committee-details/$id': typeof AuthenticatedCommitteeDetailsIdRoute
  '/cooperative-details/$id': typeof AuthenticatedCooperativeDetailsIdRoute
  '/cooperative-verification/$id': typeof AuthenticatedCooperativeVerificationIdRoute
  '/reports/detail': typeof AuthenticatedReportsDetailRoute
  '/reports/summary': typeof AuthenticatedReportsSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cooperative-form': typeof CooperativeFormRoute
  '/debug-auth': typeof DebugAuthRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/complete-registration': typeof AuthenticatedCompleteRegistrationRoute
  '/coop-profile': typeof AuthenticatedCoopProfileRoute
  '/cooperative-list': typeof AuthenticatedCooperativeListRoute
  '/cooperative-member-list': typeof AuthenticatedCooperativeMemberListRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fiscal-year': typeof AuthenticatedFiscalYearRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/verify-detail': typeof AuthenticatedVerifyDetailRoute
  '/committee-details/$id': typeof AuthenticatedCommitteeDetailsIdRoute
  '/cooperative-details/$id': typeof AuthenticatedCooperativeDetailsIdRoute
  '/cooperative-verification/$id': typeof AuthenticatedCooperativeVerificationIdRoute
  '/reports/detail': typeof AuthenticatedReportsDetailRoute
  '/reports/summary': typeof AuthenticatedReportsSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cooperative-form': typeof CooperativeFormRoute
  '/debug-auth': typeof DebugAuthRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/_authenticated/complete-registration': typeof AuthenticatedCompleteRegistrationRoute
  '/_authenticated/coop-profile': typeof AuthenticatedCoopProfileRoute
  '/_authenticated/cooperative-list': typeof AuthenticatedCooperativeListRoute
  '/_authenticated/cooperative-member-list': typeof AuthenticatedCooperativeMemberListRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fiscal-year': typeof AuthenticatedFiscalYearRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/verify-detail': typeof AuthenticatedVerifyDetailRoute
  '/_authenticated/committee-details/$id': typeof AuthenticatedCommitteeDetailsIdRoute
  '/_authenticated/cooperative-details/$id': typeof AuthenticatedCooperativeDetailsIdRoute
  '/_authenticated/cooperative-verification/$id': typeof AuthenticatedCooperativeVerificationIdRoute
  '/_authenticated/reports/detail': typeof AuthenticatedReportsDetailRoute
  '/_authenticated/reports/summary': typeof AuthenticatedReportsSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cooperative-form'
    | '/debug-auth'
    | '/login'
    | '/register'
    | '/verify-otp'
    | '/complete-registration'
    | '/coop-profile'
    | '/cooperative-list'
    | '/cooperative-member-list'
    | '/dashboard'
    | '/fiscal-year'
    | '/profile'
    | '/settings'
    | '/verify-detail'
    | '/committee-details/$id'
    | '/cooperative-details/$id'
    | '/cooperative-verification/$id'
    | '/reports/detail'
    | '/reports/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cooperative-form'
    | '/debug-auth'
    | '/login'
    | '/register'
    | '/verify-otp'
    | '/complete-registration'
    | '/coop-profile'
    | '/cooperative-list'
    | '/cooperative-member-list'
    | '/dashboard'
    | '/fiscal-year'
    | '/profile'
    | '/settings'
    | '/verify-detail'
    | '/committee-details/$id'
    | '/cooperative-details/$id'
    | '/cooperative-verification/$id'
    | '/reports/detail'
    | '/reports/summary'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cooperative-form'
    | '/debug-auth'
    | '/login'
    | '/register'
    | '/verify-otp'
    | '/_authenticated/complete-registration'
    | '/_authenticated/coop-profile'
    | '/_authenticated/cooperative-list'
    | '/_authenticated/cooperative-member-list'
    | '/_authenticated/dashboard'
    | '/_authenticated/fiscal-year'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/verify-detail'
    | '/_authenticated/committee-details/$id'
    | '/_authenticated/cooperative-details/$id'
    | '/_authenticated/cooperative-verification/$id'
    | '/_authenticated/reports/detail'
    | '/_authenticated/reports/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CooperativeFormRoute: typeof CooperativeFormRoute
  DebugAuthRoute: typeof DebugAuthRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug-auth': {
      id: '/debug-auth'
      path: '/debug-auth'
      fullPath: '/debug-auth'
      preLoaderRoute: typeof DebugAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cooperative-form': {
      id: '/cooperative-form'
      path: '/cooperative-form'
      fullPath: '/cooperative-form'
      preLoaderRoute: typeof CooperativeFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/verify-detail': {
      id: '/_authenticated/verify-detail'
      path: '/verify-detail'
      fullPath: '/verify-detail'
      preLoaderRoute: typeof AuthenticatedVerifyDetailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fiscal-year': {
      id: '/_authenticated/fiscal-year'
      path: '/fiscal-year'
      fullPath: '/fiscal-year'
      preLoaderRoute: typeof AuthenticatedFiscalYearRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cooperative-member-list': {
      id: '/_authenticated/cooperative-member-list'
      path: '/cooperative-member-list'
      fullPath: '/cooperative-member-list'
      preLoaderRoute: typeof AuthenticatedCooperativeMemberListRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cooperative-list': {
      id: '/_authenticated/cooperative-list'
      path: '/cooperative-list'
      fullPath: '/cooperative-list'
      preLoaderRoute: typeof AuthenticatedCooperativeListRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coop-profile': {
      id: '/_authenticated/coop-profile'
      path: '/coop-profile'
      fullPath: '/coop-profile'
      preLoaderRoute: typeof AuthenticatedCoopProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/complete-registration': {
      id: '/_authenticated/complete-registration'
      path: '/complete-registration'
      fullPath: '/complete-registration'
      preLoaderRoute: typeof AuthenticatedCompleteRegistrationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/summary': {
      id: '/_authenticated/reports/summary'
      path: '/reports/summary'
      fullPath: '/reports/summary'
      preLoaderRoute: typeof AuthenticatedReportsSummaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/detail': {
      id: '/_authenticated/reports/detail'
      path: '/reports/detail'
      fullPath: '/reports/detail'
      preLoaderRoute: typeof AuthenticatedReportsDetailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cooperative-verification/$id': {
      id: '/_authenticated/cooperative-verification/$id'
      path: '/cooperative-verification/$id'
      fullPath: '/cooperative-verification/$id'
      preLoaderRoute: typeof AuthenticatedCooperativeVerificationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cooperative-details/$id': {
      id: '/_authenticated/cooperative-details/$id'
      path: '/cooperative-details/$id'
      fullPath: '/cooperative-details/$id'
      preLoaderRoute: typeof AuthenticatedCooperativeDetailsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/committee-details/$id': {
      id: '/_authenticated/committee-details/$id'
      path: '/committee-details/$id'
      fullPath: '/committee-details/$id'
      preLoaderRoute: typeof AuthenticatedCommitteeDetailsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCompleteRegistrationRoute: typeof AuthenticatedCompleteRegistrationRoute
  AuthenticatedCoopProfileRoute: typeof AuthenticatedCoopProfileRoute
  AuthenticatedCooperativeListRoute: typeof AuthenticatedCooperativeListRoute
  AuthenticatedCooperativeMemberListRoute: typeof AuthenticatedCooperativeMemberListRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFiscalYearRoute: typeof AuthenticatedFiscalYearRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVerifyDetailRoute: typeof AuthenticatedVerifyDetailRoute
  AuthenticatedCommitteeDetailsIdRoute: typeof AuthenticatedCommitteeDetailsIdRoute
  AuthenticatedCooperativeDetailsIdRoute: typeof AuthenticatedCooperativeDetailsIdRoute
  AuthenticatedCooperativeVerificationIdRoute: typeof AuthenticatedCooperativeVerificationIdRoute
  AuthenticatedReportsDetailRoute: typeof AuthenticatedReportsDetailRoute
  AuthenticatedReportsSummaryRoute: typeof AuthenticatedReportsSummaryRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCompleteRegistrationRoute:
    AuthenticatedCompleteRegistrationRoute,
  AuthenticatedCoopProfileRoute: AuthenticatedCoopProfileRoute,
  AuthenticatedCooperativeListRoute: AuthenticatedCooperativeListRoute,
  AuthenticatedCooperativeMemberListRoute:
    AuthenticatedCooperativeMemberListRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFiscalYearRoute: AuthenticatedFiscalYearRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVerifyDetailRoute: AuthenticatedVerifyDetailRoute,
  AuthenticatedCommitteeDetailsIdRoute: AuthenticatedCommitteeDetailsIdRoute,
  AuthenticatedCooperativeDetailsIdRoute:
    AuthenticatedCooperativeDetailsIdRoute,
  AuthenticatedCooperativeVerificationIdRoute:
    AuthenticatedCooperativeVerificationIdRoute,
  AuthenticatedReportsDetailRoute: AuthenticatedReportsDetailRoute,
  AuthenticatedReportsSummaryRoute: AuthenticatedReportsSummaryRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CooperativeFormRoute: CooperativeFormRoute,
  DebugAuthRoute: DebugAuthRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
